In [1]:
import numpy as np
from scipy.spatial.transform import Rotation

In [2]:
T_oi = [[1.0, 0.0, 0.0, 0.71],
         [0.0, 1.0, 0.0, -0.0165],
         [0.0, 0.0, 1.0, 0.42],
         [0.0, 0.0, 0.0, 1.0]]

In [3]:
T_oi

[[1.0, 0.0, 0.0, 0.71],
 [0.0, 1.0, 0.0, -0.0165],
 [0.0, 0.0, 1.0, 0.42],
 [0.0, 0.0, 0.0, 1.0]]

In [4]:
T_ci = [[0.005459969472053433, -0.9998896692056289, 0.013814418164449227, 0.0754590075458481],
         [0.0021750466690124703, -0.013802716671227067, -0.9999023723266596, -0.019547802789885316],
         [0.9999827288035288, 0.005489483432150222, 0.0020994442827294013, -0.010584573188241865],
         [0.0, 0.0, 0.0, 1.0]]

In [5]:
T_ci_inv = np.linalg.inv(T_ci)

In [6]:
T_oc = np.dot(T_oi, T_ci_inv)
T_oc

array([[ 0.00545997,  0.00217505,  0.99998273,  0.7202149 ],
       [-0.99988967, -0.01380272,  0.00548948,  0.05873897],
       [ 0.01381442, -0.99990237,  0.00209944,  0.39943391],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
R = T_oc[:3,:3]
R

array([[ 0.00545997,  0.00217505,  0.99998273],
       [-0.99988967, -0.01380272,  0.00548948],
       [ 0.01381442, -0.99990237,  0.00209944]])

In [8]:
t = T_oc[:3, 3]
t

array([0.7202149 , 0.05873897, 0.39943391])

In [10]:
rotation = Rotation.from_matrix(R)
quaternion = rotation.as_quat()
quaternion

array([ 0.51917192, -0.4892138 ,  0.50135492, -0.48966684])